Got the category list alphabetized
NSS-Day-Cohort-59/hermes-heroes-tabloidfullstack pull request #49
Opened 2023-01-24 19:48 UTC by Jesier

closes #39 
Got the category list alphabetized

2023-01-24 20:01 UTC, dalamcd requested changes

2023-01-24 20:01 UTC, dalamcd commented on Tabloid/Properties/launchSettings.json
>  {
This file should not be included in pull requests

2023-01-24 20:01 UTC, dalamcd commented on Tabloid/Controllers/CategoryController.cs
> +    public class CategoryController : ControllerBase
Need to add [Authorize] above the controller class definition to protect routes from unauthorized users

2023-01-24 20:01 UTC, dalamcd commented on Tabloid/client/src/modules/categoryManager.js
> +
Need to use the getToken() method in authManager.js to get the currently logged in user's token, and then send that to the server in the Authorization header as part of the fetch call (see _doesUserExist() and _saveUser() in authManager.js for an example of how to get the token and how to send it)

2023-01-24 20:02 UTC, dalamcd commented on Tabloid/client/src/modules/categoryManager.js
> +
This is the same for all the fetch calls, by the way, not just the one this comment is above!

2023-01-24 20:10 UTC, Jesier commented on Tabloid/Properties/launchSettings.json
>  {
I thought the git ignore did this was it not supposed to?

2023-01-25 15:55 UTC, Jesier commented
change requests done

2023-01-25 20:34 UTC, dalamcd approved these changes
Everything looks good!

2023-01-26 20:48 UTC, merged